# see https://docs.travis-ci.com/user/languages/php/ for more hints
language: php

php:
  - 7.2
#  - 7.3
#  - 7.4
#  - 8.0

before_script:
  - composer self-update
  - composer install

script:
  - ls /home/travis/build/alex-kalanis/kw_confs/
  - ls /home/travis/build/alex-kalanis/kw_confs/vendor/alex-kalanis/
  - cat /home/travis/build/alex-kalanis/kw_confs/vendor/alex-kalanis/kw_paths/php-src/Path.php
  - phpunit --configuration phpunit.xml --coverage-clover php-tests/data/clover.xml

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover php-tests/data/clover.xml

notifications:
  email: "me@kalanys.com"
